import Vuex from 'vuex'

const createStore = () =>{
	return new Vuex.Store({
		state:{
			showTip:false,
			showSearch:false,
			bannerImg:[
				'banner/banner1.jpg',
				'banner/banner2.jpg',
				'banner/banner3.jpg',
				'banner/banner4.jpg',
				'banner/banner5.jpg'
			],
			city: [
				{
					"id":"0",
					"name": "黑龙江省",
					"description": "黑龙江省",
					"img": "province/china-1.jpg",
					"area": "东北",
					"abbr":"黑",
					"info":"黑龙江省，简称黑，中华人民共和国省级行政区。省会哈尔滨，位于中国东北部，是中国位置最北、最东，纬度最高的省份，西起121°11′，东至135°05′，南起43°26′，北至53°33′，东西跨14个经度，南北跨10个纬度。北部、东部与俄罗斯隔江相望，西部与内蒙古自治区相邻，南部与吉林省接壤。全省土地总面积47.3万平方千米（含加格达奇和松岭区），居全国第6位，边境线长2981.26千米",
					"child":[
						{
							"id":"0",
							"name":"哈尔滨市",
							"sonchild":[
								{
									"id":"0",
									"name":"圣索菲亚大教堂",
									"img":'city/city1-1-1.jpeg',
									"info":'远东地区最大的东正教堂，也是哈尔滨现存的教堂中最著名、最精美的一座。'
								},
								{
									"id":"1",
									"name":"中央大街步行街",
									"img":'city/city1-1-2.jpeg',
									"info":'目前亚洲最长的，也是最繁盛的一条商业步行街。'
								},
								{
									"id":"2",
									"name":"松花江",
									"img":'city/city1-1-3.jpeg',
									"info":'中国七大河之一，黑龙江在中国境内的最大支流。'
								},
								{
									"id":"3",
									"name":"冰雪大世界",
									"img":'city/city1-1-4.jpeg',
									"info":'世界最大的冰雪主题游乐园，集天下冰雪艺术之精华。'
								},
								{
									"id":"4",
									"name":"太阳岛风景区",
									"img":'city/city1-1-5.jpeg',
									"info":'驰名中外的避暑胜地，哈尔滨的一颗亮丽明珠。'
								}
							]
						},
						{
							"id":"1",
							"name":"齐齐哈尔市",
							"sonchild":[
								{
									"id":"0",
									"name":"扎龙国家级自然保护区",
									"img":'city/city1-2-1.jpeg',
									"info":'123'
								},
								{
									"id":"1",
									"name":"龙沙公园",
									"img":'city/city1-2-2.jpeg',
									"info":'123'
								},
								{
									"id":"2",
									"name":"明月岛",
									"img":'city/city1-2-3.jpeg',
									"info":'123'
								},
								{
									"id":"3",
									"name":"和平广场",
									"img":'city/city1-2-4.jpeg',
									"info":'123'
								},
								{
									"id":"4",
									"name":"齐齐哈尔博物馆",
									"img":'city/city1-2-5.jpeg',
									"info":'123'
								}
							]
						},
						{
							"id":"2",
							"name":"牡丹江市",
							"sonchild":[
								{
									"id":"0",
									"name":"中国雪乡",
									"img":'city/city1-3-1.jpeg'
								},
								{
									"id":"1",
									"name":"镜泊湖风景区",
									"img":'city/city1-3-2.jpeg'
								},
								{
									"id":"2",
									"name":"二浪河景区",
									"img":'city/city1-3-3.jpeg'
								},
								{
									"id":"3",
									"name":"地下森林",
									"img":'city/city1-3-4.jpeg'
								},
								{
									"id":"4",
									"name":"大秃顶子山",
									"img":'city/city1-3-5.jpeg'
								}
							]
						},
						{
							"id":"3",
						 	"name":"佳木斯市",
							"sonchild":[
								{
									"id":"0",
									"name":"中国黑瞎子岛湿地公园",
									"img":'city/city1-4-1.jpeg'
								},
								{
									"id":"1",
									"name":"乌苏镇",
									"img":'city/city1-4-2.jpeg'
								},
								{
									"id":"2",
									"name":"东极宝塔",
									"img":'city/city1-4-3.jpeg'
								},
								{
									"id":"3",
									"name":"乌苏镇东方第一哨",
									"img":'city/city1-4-4.jpeg'
								},
								{
									"id":"4",
									"name":"同江三江口旅游区",
									"img":'city/city1-4-5.jpeg'
								}
							]
						},
						{
							"id":"4",
							"name":"大庆市",
							"sonchild":[
								{
									"id":"0",
									"name":"铁人王进喜纪念馆",
									"img":'city/city1-5-1.jpeg'
								},
								{
									"id":"1",
									"name":"大庆博物馆",
									"img":'city/city1-5-2.jpeg'
								},
								{
									"id":"2",
									"name":"龙凤湿地",
									"img":'city/city1-5-3.jpeg'
								},
								{
									"id":"3",
									"name":"连环湖温泉景区",
									"img":'city/city1-5-4.jpeg'
								},
								{
									"id":"4",
									"name":"北国温泉",
									"img":'city/city1-5-5.jpeg'
								}
							]
						},
						{
							"id":"5",
							"name":"鸡西市",
							"sonchild":[
								{
									"id":"0",
									"name":"兴凯湖旅游度假区",
									"img":'city/city1-6-1.jpeg'
								},
								{
									"id":"1",
									"name":"侵华日军虎头要塞遗址博物馆",
									"img":'city/city1-6-2.jpeg'
								},
								{
									"id":"2",
									"name":"兴凯湖新开流景区",
									"img":'city/city1-6-3.jpeg'
								},
								{
									"id":"3",
									"name":"珍宝岛湿地公园",
									"img":'city/city1-6-4.jpeg'
								},
								{
									"id":"4",
									"name":"乌苏里江",
									"img":'city/city1-6-5.jpeg'
								}
							]
						},
						{
							"id":"6",
							"name":"双鸭山市",
							"sonchild":[
								{
									"id":"0",
									"name":"珍宝岛",
									"img":'city/city1-7-1.jpeg'
								},
								{
									"id":"1",
									"name":"红旗岭千鸟湖景区",
									"img":'city/city1-7-2.jpeg'
								},
								{
									"id":"2",
									"name":"益寿山公园",
									"img":'city/city1-7-3.jpeg'
								},
								{
									"id":"3",
									"name":"四排赫哲风景区",
									"img":'city/city1-7-4.jpeg'
								},
								{
									"id":"4",
									"name":"安邦河国家湿地公园",
									"img":'city/city1-7-5.jpeg'
								}
							]
						},
						{
							"id":"7",
							"name":"伊春市",
							"sonchild":[
								{
									"id":"0",
									"name":"汤旺河林海奇石风景区",
									"img":'city/city1-8-1.jpeg'
								},
								{
									"id":"1",
									"name":"五营国家森林公园",
									"img":'city/city1-8-2.jpeg'
								},
								{
									"id":"2",
									"name":"茅兰沟国家森林公园",
									"img":'city/city1-8-3.jpeg'
								},
								{
									"id":"3",
									"name":"汤旺河国家公园",
									"img":'city/city1-8-4.jpeg'
								},
								{
									"id":"4",
									"name":"兴安森林公园",
									"img":'city/city1-8-5.jpeg'
								}
							]
						},
						{
							"id":"8",
							"name":"七台河市",
							"sonchild":[
								{
									"id":"0",
									"name":"桃山公园",
									"img":'city/city1-9-1.jpeg'
								},
								{
									"id":"1",
									"name":"仙洞山风景区",
									"img":'city/city1-9-2.jpeg'
								}
							]
						},
						{
							"id":"9",
							"name":"鹤岗市",
							"sonchild":[
								{
									"id":"0",
									"name":"名山岛",
									"img":'city/city1-10-1.jpeg'
								},
								{
									"id":"1",
									"name":"天水湖公园",
									"img":'city/city1-10-2.jpeg'
								},
								{
									"id":"2",
									"name":"太平沟乡",
									"img":'city/city1-10-3.jpeg'
								},
								{
									"id":"3",
									"name":"松鹤西湖公园",
									"img":'city/city1-10-4.jpeg'
								},
								{
									"id":"4",
									"name":"兴龙峡谷",
									"img":'city/city1-10-5.jpeg'
								}
							]
						},
						{
							"id":"10",
							"name":"黑河市",
							"sonchild":[
								{
									"id":"0",
									"name":"五大连池风景区",
									"img":'city/city1-11-1.jpeg'
								},
								{
									"id":"1",
									"name":"逊克大平台雾凇风景区",
									"img":'city/city1-11-2.jpeg'
								},
								{
									"id":"2",
									"name":"瑷珲历史陈列馆",
									"img":'city/city1-11-3.jpeg'
								},
								{
									"id":"3",
									"name":"五大连池世界地质公园博物馆",
									"img":'city/city1-11-4.jpeg'
								},
								{
									"id":"4",
									"name":"黑河火烧山",
									"img":'city/city1-11-5.jpeg'
								}
							]
						},
						{
							"id":"11",
							"name":"绥化市",
							"sonchild":[
								{
									"id":"0",
									"name":"东林寺",
									"img":'city/city1-12-1.jpeg'
								},
								{
									"id":"1",
									"name":"绥化学院",
									"img":'city/city1-12-2.jpeg'
								},
								{
									"id":"2",
									"name":"望奎服务区",
									"img":'city/city1-12-3.jpeg'
								}
							]
						},
						{
							"id":"12",
							"name":"大兴安岭地区",
							"sonchild":[
								{
									"id":"0",
									"name":"北极村",
									"img":'city/city1-13-1.jpeg'
								},
								{
									"id":"1",
									"name":"北红村",
									"img":'city/city1-13-2.jpeg'
								},
								{
									"id":"2",
									"name":"黑龙江第一湾",
									"img":'city/city1-13-3.jpeg'
								},
								{
									"id":"3",
									"name":"白桦林",
									"img":'city/city1-13-4.jpeg'
								},
								{
									"id":"4",
									"name":"九曲十八弯湿地公园",
									"img":'city/city1-13-5.jpeg'
								}
							]
						}
					]
				},
				{
					"id":"1",
					"name": "吉林省",
					"description": "吉林省",
					"img": "province/china-2.jpg",
					"area": "东北",
					"abbr":"吉",
					"child":[
						{
							"id":"0",
							"name":"长春市",
							"img": "china-2"
						},
						{
							"id":"1",
							"name":"吉林市",
							"img": "china-2"
						},
						{
							"id":"2",
							"name":"四平市",
							"img": "china-2"
						},
						{
							"id":"3",
						 	"name":"辽源市",
							"img": "china-2"
						},
						{
							"id":"4",
							"name":"通化市",
							"img": "china-2"
						},
						{
							"id":"5",
							"name":"白山市",
							"img": "china-2"
						},
						{
							"id":"6",
							"name":"白城市",
							"img": "china-2"
						},
						{
							"id":"7",
							"name":"松原市",
							"img": "china-2"
						},
						{
							"id":"8",
							"name":"延边朝鲜族自治州",
							"img": "china-2"
						}
					]
				},
				{
					"id":"2",
					"name": "辽宁省",
					"description": "辽宁省",
					"img": "province/china-3.jpg",
					"area": "东北",
					"abbr":"辽",
					"child":[
						{
							"name":"沈阳市"
						},
						{
							"name":"大连市"
						},
						{
							"name":"鞍山市"
						},
						{
							"name":"抚顺市"
						},
						{
							"name":"本溪市"
						},
						{
							"name":"丹东市"
						},
						{
							"name":"锦州市"
						},
						{
							"name":"阜新市"
						},
						{
							"name":"辽阳市"
						},
						{
							"name":"盘锦市"
						},
						{
							"name":"铁岭市"
						},
						{
							"name":"朝阳市"
						},
						{
							"name":"葫芦岛市"
						}
					]
				},
				{
					"id":"3",
					"name": "北京市",
					"description": "北京市",
					"img": "province/china-4.jpg",
					"area": "华北",
					"abbr":"京",
					"child":[
						{
							"name":"东城区"
						},
						{
							"name":"西城区"
						},
						{
							"name":"朝阳区"
						},
						{
							"name":"丰台区"
						},
						{
							"name":"石景山区"
						},
						{
							"name":"海淀区"
						},
						{
							"name":"顺义区"
						},
						{
							"name":"通州区"
						},
						{
							"name":"大兴区"
						},
						{
							"name":"房山区"
						},
						{
							"name":"门头沟区"
						},
						{
							"name":"昌平区"
						},
						{
							"name":"平谷区"
						},
						{
							"name":"密云区"
						},
						{
							"name":"怀柔区"
						},
						{
							"name":"延庆区"
						}
					]
				},
				{
					"id":"4",
					"name": "天津市",
					"description": "天津市",
					"img": "province/china-5.jpg",
					"area": "华北",
					"abbr":"津",
					"child":[
						{
							"name":"和平区"
						},
						{
							"name":"河东区"
						},
						{
							"name":"河西区"
						},
						{
							"name":"南开区"
						},
						{
							"name":"河北区"
						},
						{
							"name":"红桥区"
						},
						{
							"name":"滨海新区"
						},
						{
							"name":"东丽区"
						},
						{
							"name":"西青区"
						},
						{
							"name":"津南区"
						},
						{
							"name":"北辰区"
						},
						{
							"name":"武清区"
						},
						{
							"name":"宝坻区"
						},
						{
							"name":"宁河区"
						},
						{
							"name":"静海区"
						},
						{
							"name":"蓟州区"
						}
					]
				},
				{
					"id":"5",
					"name": "河北省",
					"description": "河北省",
					"img": "province/china-6.jpg",
					"area": "华北",
					"abbr":"冀",
					"child":[
						{
							"name":"石家庄市"
						},
						{
							"name":"唐山市"
						},
						{
							"name":"秦皇岛市"
						},
						{
							"name":"邯郸市"
						},
						{
							"name":"邢台市"
						},
						{
							"name":"张家口市"
						},
						{
							"name":"承德市"
						},
						{
							"name":"沧州市"
						},
						{
							"name":"廊坊市"
						},
						{
							"name":"衡水市"
						}
					]
				},
				{
					"id":"6",
					"name": "山西省",
					"description": "山西省",
					"img": "province/china-7.jpg",
					"area": "华北",
					"abbr":"晋",
					"child":[
						{
							"name":"太原市"
						},
						{
							"name":"大同市"
						},
						{
							"name":"朔州市"
						},
						{
							"name":"忻州市"
						},
						{
							"name":"阳泉市"
						},
						{
							"name":"吕梁市"
						},
						{
							"name":"晋中市"
						},
						{
							"name":"长治市"
						},
						{
							"name":"晋城市"
						},
						{
							"name":"临汾市"
						},
						{
							"name":"运城市"
						}
					]
				},
				{
					"id":"7",
					"name": "内蒙古自治区",
					"description": "内蒙古自治区",
					"img": "province/china-8.jpg",
					"area": "华北",
					"abbr":"内蒙古",
					"child":[
						{
							"name":"呼和浩特市"
						},
						{
							"name":"包头市"
						},
						{
							"name":"乌海市"
						},
						{
							"name":"赤峰市"
						},
						{
							"name":"通辽市"
						},
						{
							"name":"鄂尔多斯市"
						},
						{
							"name":"呼伦贝尔市"
						},
						{
							"name":"巴彦淖尔市"
						},
						{
							"name":"乌兰察布市"
						},
						{
							"name":"兴安盟"
						},
						{
							"name":"锡林郭勒盟"
						},
						{
							"name":"阿拉善盟"
						}
					]
				},
				{
					"id":"8",
					"name": "宁夏回族自治区",
					"description": "宁夏回族自治区",
					"img": "province/china-9.jpg",
					"area": "西北",
					"abbr":"宁",
					"child":[
						{
							"name":"银川市"
						},
						{
							"name":"石嘴山市"
						},
						{
							"name":"吴忠市"
						},
						{
							"name":"固原市"
						},
						{
							"name":"中卫市"
						}
					]
				},
				{
					"id":"9",
					"name": "新疆维吾尔自治区",
					"description": "新疆维吾尔自治区",
					"img": "province/china-10.jpg",
					"area": "西北",
					"abbr":"新",
					"child":[
						{
							"name":"乌鲁木齐市"
						},
						{
							"name":"克拉玛依市"
						},
						{
							"name":"吐鲁番市"
						},
						{
							"name":"哈密市"
						},
						{
							"name":"阿克苏地区"
						},
						{
							"name":"和田地区"
						},
						{
							"name":"昌吉回族自治州"
						},
						{
							"name":"博尔塔拉蒙古自治州"
						},
						{
							"name":"巴音郭楞蒙古自治州"
						},
						{
							"name":"克孜勒苏柯尔克孜自治州"
						},
						{
							"name":"伊犁哈萨克自治州"
						},
						{
							"name":"塔城地区"
						},
						{
							"name":"阿勒泰地区"
						}
					]
				},
				{
					"id":"10",
					"name": "青海省",
					"description": "青海省",
					"img": "province/china-11.jpg",
					"area": "西北",
					"abbr":"青",
					"child":[
						{
							"name":"西宁市"
						},
						{
							"name":"海东市"
						},
						{
							"name":"海北藏族自治州"
						},
						{
							"name":"黄南藏族自治州"
						},
						{
							"name":"海南藏族自治州"
						},
						{
							"name":"果洛藏族自治州"
						},
						{
							"name":"玉树藏族自治州"
						},
						{
							"name":"海西蒙古族藏族自治州"
						}
					]
				},
				{
					"id":"11",
					"name": "陕西省",
					"description": "陕西省",
					"img": "province/china-12.jpg",
					"area": "西北",
					"abbr":"陕/秦",
					"child":[
						{
							"name":"西安市"
						},
						{
							"name":"宝鸡市"
						},
						{
							"name":"咸阳市"
						},
						{
							"name":"铜川市"
						},
						{
							"name":"渭南市"
						},
						{
							"name":"延安市"
						},
						{
							"name":"榆林市"
						},
						{
							"name":"汉中市"
						},
						{
							"name":"安康市"
						},
						{
							"name":"商洛市"
						}
					]
				},
				{
					"id":"12",
					"name": "甘肃省",
					"description": "甘肃省",
					"img": "province/china-13.jpg",
					"area": "西北",
					"abbr":"甘/陇",
					"child":[
						{
							"name":"兰州市"
						},
						{
							"name":"嘉峪关市"
						},
						{
							"name":"金昌市"
						},
						{
							"name":"白银市"
						},
						{
							"name":"天水市"
						},
						{
							"name":"武威市"
						},
						{
							"name":"张掖市"
						},
						{
							"name":"平凉市"
						},
						{
							"name":"酒泉市"
						},
						{
							"name":"庆阳市"
						},
						{
							"name":"定西市"
						},
						{
							"name":"陇南市"
						},
						{
							"name":"临夏回族自治州"
						},
						{
							"name":"甘南藏族自治州"
						}
					]
				},
				{
					"id":"13",
					"name": "山东省",
					"description": "山东省",
					"img": "province/china-14.jpg",
					"area": "华东",
					"abbr":"鲁",
					"child":[
						{
							"name":"济南市"
						},
						{
							"name":"青岛市"
						},
						{
							"name":"淄博市"
						},
						{
							"name":"枣庄市"
						},
						{
							"name":"东营市"
						},
						{
							"name":"烟台市"
						},
						{
							"name":"潍坊市"
						},
						{
							"name":"济宁市"
						},
						{
							"name":"泰安市"
						},
						{
							"name":"威海市"
						},
						{
							"name":"日照市"
						},
						{
							"name":"滨州市"
						},
						{
							"name":"德州市"
						},
						{
							"name":"聊城市"
						},
						{
							"name":"临沂市"
						},
						{
							"name":"菏泽市"
						},
						{
							"name":"莱芜市"
						}
					]
				},
				{
					"id":"14",
					"name": "江苏省",
					"description": "江苏省",
					"img": "province/china-15.jpg",
					"area": "华东",
					"abbr":"苏",
					"child":[
						{
							"name":"南京市"
						},
						{
							"name":"无锡市"
						},
						{
							"name":"徐州市"
						},
						{
							"name":"常州市"
						},
						{
							"name":"苏州市"
						},
						{
							"name":"南通市"
						},
						{
							"name":"连云港市"
						},
						{
							"name":"淮安市"
						},
						{
							"name":"盐城市"
						},
						{
							"name":"扬州市"
						},
						{
							"name":"镇江市"
						},
						{
							"name":"泰州市"
						},
						{
							"name":"宿迁市"
						}
					]
				},
				{
					"id":"15",
					"name": "安徽省",
					"description": "安徽省",
					"img": "province/china-16.jpg",
					"area": "华东",
					"abbr":"皖",
					"child":[
						{
							"name":"合肥市"
						},
						{
							"name":"芜湖市"
						},
						{
							"name":"蚌埠市"
						},
						{
							"name":"淮南市"
						},
						{
							"name":"马鞍山市"
						},
						{
							"name":"淮北市"
						},
						{
							"name":"铜陵市"
						},
						{
							"name":"安庆市"
						},
						{
							"name":"黄山市"
						},
						{
							"name":"阜阳市"
						},
						{
							"name":"宿州市"
						},
						{
							"name":"滁州市"
						},
						{
							"name":"六安市"
						},
						{
							"name":"宣城市"
						},
						{
							"name":"池州市"
						},
						{
							"name":"亳州市"
						}
					]
				},
				{
					"id":"16",
					"name": "浙江省",
					"description": "浙江省",
					"img": "province/china-17.jpg",
					"area": "华东",
					"abbr":"浙",
					"child":[
						{
							"name":"杭州市"
						},
						{
							"name":"宁波市"
						},
						{
							"name":"温州市"
						},
						{
							"name":"绍兴市"
						},
						{
							"name":"湖州市"
						},
						{
							"name":"嘉兴市"
						},
						{
							"name":"金华市"
						},
						{
							"name":"衢州市"
						},
						{
							"name":"台州市"
						},
						{
							"name":"丽水市"
						},
						{
							"name":"舟山市"
						}
					]
				},
				{
					"id":"17",
					"name": "福建省",
					"description": "福建省",
					"img": "province/china-18.jpg",
					"area": "华东",
					"abbr":"闽",
					"child":[
						{
							"name":"福州市"
						},
						{
							"name":"厦门市"
						},
						{
							"name":"漳州市"
						},
						{
							"name":"泉州市"
						},
						{
							"name":"三明市"
						},
						{
							"name":"莆田市"
						},
						{
							"name":"龙岩市"
						},
						{
							"name":"宁德市"
						},
						{
							"name":"平潭综合实验区"
						}
					]
				},
				{
					"id":"18",
					"name": "上海市",
					"description": "上海市",
					"img": "province/china-19.jpg",
					"area": "华东",
					"abbr":"沪",
					"child":[
						{
							"name":"黄浦区"
						},
						{
							"name":"徐汇区"
						},
						{
							"name":"长宁区"
						},
						{
							"name":"静安区"
						},
						{
							"name":"普陀区"
						},
						{
							"name":"虹口区"
						},
						{
							"name":"杨浦区"
						},
						{
							"name":"浦东新区"
						},
						{
							"name":"闵行区"
						},
						{
							"name":"宝山区"
						},
						{
							"name":"嘉定区"
						},
						{
							"name":"金山区"
						},
						{
							"name":"松江区"
						},
						{
							"name":"青浦区"
						},
						{
							"name":"奉贤区"
						},
						{
							"name":"崇明区"
						}
					]
				},
				{
					"id":"19",
					"name": "湖北省",
					"description": "湖北省",
					"img": "province/china-20.jpg",
					"area": "华中",
					"abbr":"鄂",
					"child":[
						{
							"name":"武汉市"
						},
						{
							"name":"黄石市"
						},
						{
							"name":"十堰市"
						},
						{
							"name":"宜昌市"
						},
						{
							"name":"襄阳市"
						},
						{
							"name":"鄂州市"
						},
						{
							"name":"荆门市"
						},
						{
							"name":"孝感市"
						},
						{
							"name":"荆州市"
						},
						{
							"name":"黄冈市"
						},
						{
							"name":"咸宁市"
						},
						{
							"name":"随州市"
						},
						{
							"name":"恩施土家族苗族自治州"
						}
					]
				},
				{
					"id":"20",
					"name": "湖南省",
					"description": "湖南省",
					"img": "province/china-21.jpg",
					"area": "华中",
					"abbr":"湘",
					"child":[
						{
							"name":"长沙市"
						},
						{
							"name":"株洲市"
						},
						{
							"name":"湘潭市"
						},
						{
							"name":"衡阳市"
						},
						{
							"name":"襄阳市"
						},
						{
							"name":"邵阳市"
						},
						{
							"name":"岳阳市"
						},
						{
							"name":"常德市"
						},
						{
							"name":"张家界市"
						},
						{
							"name":"益阳市"
						},
						{
							"name":"娄底市"
						},
						{
							"name":"郴州市"
						},
						{
							"name":"永州市"
						},
						{
							"name":"怀化市"
						},
						{
							"name":"湘西土家族苗族自治州"
						}
					]
				},
				{
					"id":"21",
					"name": "河南省",
					"description": "河南省",
					"img": "province/china-22.jpg",
					"area": "华中",
					"abbr":"豫",
					"child":[
						{
							"name":"郑州市"
						},
						{
							"name":"开封市"
						},
						{
							"name":"洛阳市"
						},
						{
							"name":"平顶山市"
						},
						{
							"name":"安阳市"
						},
						{
							"name":"鹤壁市"
						},
						{
							"name":"新乡市"
						},
						{
							"name":"焦作市"
						},
						{
							"name":"濮阳市"
						},
						{
							"name":"许昌市"
						},
						{
							"name":"漯河市"
						},
						{
							"name":"三门峡市"
						},
						{
							"name":"商丘市"
						},
						{
							"name":"周口市"
						},
						{
							"name":"驻马店市"
						},
						{
							"name":"南阳市"
						},
						{
							"name":"信阳市"
						},
						{
							"name":"济源市"
						}
					]
				},
				{
					"id":"22",
					"name": "江西省",
					"description": "江西省",
					"img": "province/china-23.jpg",
					"area": "华东",
					"abbr":"赣",
					"child":[
						{
							"name":"南昌市"
						},
						{
							"name":"九江市"
						},
						{
							"name":"上饶市"
						},
						{
							"name":"抚州市"
						},
						{
							"name":"宜春市"
						},
						{
							"name":"吉安市"
						},
						{
							"name":"赣州市"
						},
						{
							"name":"景德镇市"
						},
						{
							"name":"萍乡市"
						},
						{
							"name":"新余市"
						},
						{
							"name":"鹰潭市"
						}
					]
				},
				{
					"id":"23",
					"name": "四川省",
					"description": "四川省",
					"img": "province/china-24.jpg",
					"area": "西南",
					"abbr":"川/蜀",
					"child":[
						{
							"name":"成都市"
						},
						{
							"name":"绵阳市"
						},
						{
							"name":"自贡市"
						},
						{
							"name":"攀枝花市"
						},
						{
							"name":"泸州市"
						},
						{
							"name":"德阳市"
						},
						{
							"name":"广元市"
						},
						{
							"name":"遂宁市"
						},
						{
							"name":"内江市"
						},
						{
							"name":"乐山市"
						},
						{
							"name":"资阳市"
						},
						{
							"name":"宜宾市"
						},
						{
							"name":"南充市"
						},
						{
							"name":"达州市"
						},
						{
							"name":"雅安市"
						},
						{
							"name":"阿坝藏族羌族自治州"
						},
						{
							"name":"甘孜藏族自治州"
						},
						{
							"name":"凉山彝族自治州"
						},
						{
							"name":"广安市"
						},
						{
							"name":"巴中市"
						},
						{
							"name":"眉山市"
						}
					]
				},
				{
					"id":"24",
					"name": "云南省",
					"description": "云南省",
					"img": "province/china-25.jpg",
					"area": "西南",
					"abbr":"云/滇",
					"child":[
						{
							"name":"昆明市"
						},
						{
							"name":"曲靖市"
						},
						{
							"name":"玉溪市"
						},
						{
							"name":"昭通市"
						},
						{
							"name":"保山市"
						},
						{
							"name":"丽江市"
						},
						{
							"name":"普洱市"
						},
						{
							"name":"临沧市"
						},
						{
							"name":"德宏傣族景颇族自治州"
						},
						{
							"name":"怒江傈僳族自治州"
						},
						{
							"name":"迪庆藏族自治州"
						},
						{
							"name":"大理白族自治州"
						},
						{
							"name":"楚雄彝族自治州"
						},
						{
							"name":"红河哈尼族彝族自治州"
						},
						{
							"name":"文山壮族苗族自治州"
						},
						{
							"name":"西双版纳傣族自治州"
						}
					]
				},
				{
					"id":"25",
					"name": "贵州省",
					"description": "贵州省",
					"img": "province/china-26.jpg",
					"area": "西南",
					"abbr":"贵/黔",
					"child":[
						{
							"name":"贵阳市"
						},
						{
							"name":"遵义市"
						},
						{
							"name":"六盘水市"
						},
						{
							"name":"安顺市"
						},
						{
							"name":"毕节市"
						},
						{
							"name":"铜仁市"
						},
						{
							"name":"黔东南苗族侗族自治州"
						},
						{
							"name":"黔南布依族苗族自治州"
						},
						{
							"name":"德宏傣族景颇族自治州"
						},
						{
							"name":"黔西南布依族苗族自治州"
						}
					]
				},
				{
					"id":"26",
					"name": "西藏自治区",
					"description": "西藏自治区",
					"img": "province/china-27.jpg",
					"area": "西南",
					"abbr":"藏",
					"child":[
						{
							"name":"拉萨市"
						},
						{
							"name":"日喀则市"
						},
						{
							"name":"昌都市"
						},
						{
							"name":"山南市"
						},
						{
							"name":"那曲市"
						},
						{
							"name":"阿里地区"
						}
					]
				},
				{
					"id":"27",
					"name": "重庆市",
					"description": "重庆市",
					"img": "province/china-28.jpg",
					"area": "西南",
					"abbr":"渝/巴",
					"child":[
						{
							"name":"渝中区"
						},
						{
							"name":"万州区"
						},
						{
							"name":"涪陵区"
						},
						{
							"name":"大渡口区"
						},
						{
							"name":"江北区"
						},
						{
							"name":"沙坪坝区"
						},
						{
							"name":"九龙坡区"
						},
						{
							"name":"南岸区"
						},
						{
							"name":"北碚区"
						},
						{
							"name":"綦江区"
						},
						{
							"name":"大足区"
						},
						{
							"name":"渝北区"
						},
						{
							"name":"巴南区"
						},
						{
							"name":"黔江区"
						},
						{
							"name":"长寿区"
						},
						{
							"name":"江津区"
						},
						{
							"name":"合川区"
						},
						{
							"name":"永川区"
						},
						{
							"name":"南川区"
						},
						{
							"name":"璧山区"
						},
						{
							"name":"铜梁区"
						},
						{
							"name":"潼南区"
						},
						{
							"name":"荣昌区"
						},
						{
							"name":"开州区"
						},
						{
							"name":"梁平区"
						},
						{
							"name":"武隆区"
						},
						{
							"name":"城口县"
						},
						{
							"name":"丰都县"
						},
						{
							"name":"垫江县"
						},
						{
							"name":"忠县"
						},
						{
							"name":"云阳县"
						},
						{
							"name":"奉节县"
						},
						{
							"name":"巫山县"
						},
						{
							"name":"巫溪县"
						},
						{
							"name":"石柱土家族自治县"
						},
						{
							"name":"秀山土家族苗族自治县"
						},
						{
							"name":"酉阳土家族苗族自治县"
						},
						{
							"name":"彭水苗族土家族自治县"
						}
					]
				},
				{
					"id":"28",
					"name": "广东省",
					"description": "广东省",
					"img": "province/china-29.jpg",
					"area": "华南",
					"abbr":"粤",
					"child":[
						{
							"name":"广州市"
						},
						{
							"name":"深圳市"
						},
						{
							"name":"珠海市"
						},
						{
							"name":"汕头市"
						},
						{
							"name":"佛山市"
						},
						{
							"name":"韶关市"
						},
						{
							"name":"湛江市"
						},
						{
							"name":"肇庆市"
						},
						{
							"name":"江门市"
						},
						{
							"name":"茂名市"
						},
						{
							"name":"惠州市"
						},
						{
							"name":"梅州市"
						},
						{
							"name":"汕尾市"
						},
						{
							"name":"河源市"
						},
						{
							"name":"阳江市"
						},
						{
							"name":"清远市"
						},
						{
							"name":"东莞市"
						},
						{
							"name":"中山市"
						},
						{
							"name":"潮州市"
						},
						{
							"name":"揭阳市"
						},
						{
							"name":"云浮市"
						}
					]
				},
				{
					"id":"29",
					"name": "广西壮族自治区",
					"description": "广西壮族自治区",
					"img": "province/china-30.jpg",
					"area": "华南",
					"abbr":"桂",
					"child":[
						{
							"name":"南宁市"
						},
						{
							"name":"柳州市"
						},
						{
							"name":"桂林市"
						},
						{
							"name":"梧州市"
						},
						{
							"name":"北海市"
						},
						{
							"name":"防城港市"
						},
						{
							"name":"钦州市"
						},
						{
							"name":"贵港市"
						},
						{
							"name":"玉林市"
						},
						{
							"name":"百色市"
						},
						{
							"name":"贺州市"
						},
						{
							"name":"河池市"
						},
						{
							"name":"来宾市"
						},
						{
							"name":"崇左市"
						}
					]
				},
				{
					"id":"30",
					"name": "海南省",
					"description": "海南省",
					"img": "province/china-31.jpg",
					"area": "华南",
					"abbr":"琼",
					"child":[
						{
							"name":"海口市"
						},
						{
							"name":"三亚市"
						},
						{
							"name":"三沙市"
						},
						{
							"name":"儋州市"
						},
						{
							"name":"定安县"
						},
						{
							"name":"屯昌县"
						},
						{
							"name":"澄迈县"
						},
						{
							"name":"临高县"
						},
						{
							"name":"五指山市"
						},
						{
							"name":"文昌市"
						},
						{
							"name":"琼海市"
						},
						{
							"name":"万宁市"
						},
						{
							"name":"东方市"
						},
						{
							"name":"白沙黎族自治县"
						},
						{
							"name":"昌江黎族自治县"
						},
						{
							"name":"乐东黎族自治县"
						},
						{
							"name":"陵水黎族自治县"
						},
						{
							"name":"保亭黎族苗族自治县"
						},
						{
							"name":"琼中黎族苗族自治县"
						},
						{
							"name":"干冲区"
						},
						{
							"name":"新英湾区"
						},
						{
							"name":"三都区"
						}
					]
				},
				{
					"id":"31",
					"name": "台湾省",
					"description": "台湾省",
					"img": "province/china-32.jpg",
					"area": "华东",
					"abbr":"台",
					"child":[
						{
							"name":"台北市"
						},
						{
							"name":"新北市"
						},
						{
							"name":"桃园市"
						},
						{
							"name":"台中市"
						},
						{
							"name":"台南市"
						},
						{
							"name":"高雄市"
						},
						{
							"name":"基隆市"
						},
						{
							"name":"新竹市"
						},
						{
							"name":"嘉义市"
						}
					]
				},
				{
					"id":"32",
					"name": "香港特别行政区",
					"description": "香港特别行政区",
					"img": "province/china-33.jpg",
					"area": "华南",
					"abbr":"港",
					"child":[
						{
							"name":"中西区"
						},
						{
							"name":"湾仔区"
						},
						{
							"name":"东区"
						},
						{
							"name":"南区"
						},
						{
							"name":"台南油尖旺区市"
						},
						{
							"name":"深水埗区"
						},
						{
							"name":"九龙城区"
						},
						{
							"name":"黄大仙区"
						},
						{
							"name":"观塘区"
						},
						{
							"name":"北区"
						},
						{
							"name":"大埔区"
						},
						{
							"name":"沙田区"
						},
						{
							"name":"西贡区"
						},
						{
							"name":"荃湾区"
						},
						{
							"name":"屯门区"
						},
						{
							"name":"元朗区"
						},
						{
							"name":"葵青区"
						},
						{
							"name":"离岛区"
						}
					]
				},
				{
					"id":"33",
					"name": "澳门特别行政区",
					"description": "澳门特别行政区",
					"img": "province/china-34.jpg",
					"area": "华南",
					"abbr":"澳",
					"child":[
						{
							"name":"花地玛堂区"
						},
						{
							"name":"圣安多尼堂区"
						},
						{
							"name":"大堂区"
						},
						{
							"name":"南区"
						},
						{
							"name":"望德堂区"
						},
						{
							"name":"风顺堂区（圣老愣佐堂区）"
						},
						{
							"name":"嘉模堂区"
						},
						{
							"name":"圣方济各堂区"
						},
						{
							"name":"路氹城"
						}
					]
				}
			]
		},
		mutations:{
			getItem(state,payload){
				this.state.selectItem = payload.item
				// console.log(this.state.setItem)
			},
			changeShow(state,payload){
				this.state.showSearch = payload
			}
		}
	})
}

export default createStore;